### ISSUE TITLE
Memory not released till item is read

### ISSUE THREAD

**Issue by basarat** [SamVerschueren/expiry-map#2]
Items stored will stay in memory till you try to read the key at which point its cleared from the internal `Map`. 

Solution: Change behavior OR mention in README

**Comment by basarat** [comment]
PS: Nice project. Thanks for sharing :rose:

**Comment by SamVerschueren** [comment]
Thanks for the suggestions @basarat! I think I came up with a nice solution. Have to test things out first though.

**Comment by SamVerschueren** [comment]
Fixed and released in `1.1.0` :tada:
